### ISSUE TITLE
Error when running TabulaMurisSenisDroplet(tissues = "All")

### ISSUE THREAD

**Issue by flugende** [fmicompbio/TabulaMurisSenisData#16]
Hi,

just wanted to use your package to retrieve the TabulaMurisSensisData. 
However, running  `TabulaMurisSenisDroplet(tissues = "All")`results in  
**snapshotDate(): 2020-10-27
Error in .getHubRecord(hub = hub, host = host, tissue = ts, suffix = "_counts.h5") : 
  (All) Error - expected a single counts.h5 file**

"TabulaMurisSenisData/tabula-muris-senis-droplet" also doesn't seem to be in hub$rdatapath
`hub <- ExperimentHub::ExperimentHub() `
`host <- file.path("TabulaMurisSenisData", "tabula-muris-senis-droplet") `
`tissue <- "All"`
`suffix = "_counts.h5"`
`hub[hub$rdatapath ==  file.path(host, paste0(tissue, suffix))]`
**ExperimentHub with 0 records
 snapshotDate(): 2020-10-27** 

and `grep("muris", hub$rdatapath, value=TRUE, ignore.case = T)` just shows
**[1] "TabulaMurisData/TabulaMurisDroplet.rds"    
[2] "TabulaMurisData/TabulaMurisSmartSeq2.rds"  
[3] "clustifyrdatahub/ref_tabula_muris_drop.rda"
[4] "clustifyrdatahub/ref_tabula_muris_facs.rda"**

**Comment by csoneson** [comment]
Yes, that's correct - to access the data you need to use the [development](https://www.bioconductor.org/developers/how-to/useDevel/) version of Bioconductor (which will become the next release by the end of October).

**Comment by flugende** [comment]
I see, thank you. Would suggest mentioning it in the README or in the DESCRIPTION file as a dependency.

**Comment by csoneson** [comment]
I was about to add it to the README, but in fact the information is already there :) 
Here: 

```
Note that R version 4.1 or newer, and Bioconductor release 3.14 (current devel version) or newer are required to use the package.
```

**Comment by flugende** [comment]
Sorry, next time I should read more carefully... :)
